spring.application.name=LebronHouse

mqtt.broker=tcp://localhost:1883
mqtt.topic=home/sensors
mqtt.client.id=spring-iot-server

influx.url=http://localhost:8086
influx.token=ELO3p_ybZ1UOLbyauhbMlPppbpIaqSAyejlM5UruiB5kiW-pJ3y7Oyg4Gg3-cBUg5wGofSF2ynXCtq0ieGo-rw==
influx.org=iot
influx.bucket=home
