spring.application.name=LebronHouse

mqtt.broker=tcp://localhost:1883
mqtt.topic=home/sensors
mqtt.client.id=spring-iot-server

mqtt.outbound.topic=home/all
mqtt.outbound.topic.PI3=home/PI3
mqtt.outbound.topic.PI2=home/PI2


influx.url=http://localhost:8086
influx.token=OjTTgfMTK4wrny9DYawRcJWuYTNKM7y_hgqj4EPLpZdfCVJ1W0P87mHl77nP9t_vCBmJ3pVwQ7YfxX9mJPWELw==
influx.org=iot
influx.bucket=home

house.config.pin=6236
