{
 "title": "PI One Dash",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DB\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "DMS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DMS\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "DL",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -60m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DL\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r._value == true then 1.0 else 0.0\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "DS1",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DS1\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r._value then 1 else 0\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "DPIR1",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DPIR1\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r._value == true then 1.0 else 0.0\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "DUS1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DUS1\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> yield(name: \"DUS1\")\r\n"
    }
   ]
  }
 ]
}